#%RAML 0.8
title: PetStore
version: 1.1
baseUri: http://mocksvc.mulesoft.com/mocks/xxxx/{version}

/users:
  /user:
    /authentication:
      displayName: user authentication
      post:
        description: user authentication
        body:
          application/json:
        responses:
          200:
            body:
              application/json:
    /userInfo:
      displayName: user all Information
      post:
        description: user all Information
        body:
          application/json:
        responses:
          200:
            body:
              application/json:
/notExists:
  displayName: user authentication
  get:
    description: user authentication
    responses:
      200:
        body:
          application/json: